In [43]:
print("Hello RAHUL")

Hello RAHUL


In [44]:
import random
import pandas as pd
import csv

In [45]:
import numpy as np

In [46]:
# 1. Write a NumPy program to create an array with the values 1, 7, 13, 105    
# and determine the size of the memory occupied by the array.

arr = np.array([0,1,7,13,105])
print(arr)
print(arr.size)
print(arr.itemsize)

print(f"Memmory : {(arr.size) * (arr.itemsize)} ")

[  0   1   7  13 105]
5
8
Memmory : 40 


In [47]:
# 2. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

arr1 = np.array([1,3,1,10,5])
arr2 = np.array([1,3,1,10,5])
arr3 = np.array([5,1,1,9,7])

print(arr1 == arr2)
print(arr3 > arr2)
print(arr3 < arr2)

[ True  True  True  True  True]
[ True False False False  True]
[False  True False  True False]


In [48]:
# 3. Write a NumPy program to create an array of integers from 30 to 70

arr = np.arange(30,71)
print(arr)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [49]:
# 4. Write a NumPy program to create an array of all even integers from 20 to 80

arr = np.arange(20,81,2)
 
print(arr)



[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [50]:
# 5. Write a NumPy program to create an array of all odd integers from 20 to 80

print(np.arange(21,81,2))

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [51]:
# 6. Write a NumPy program to generate an array of 15 random numbers from 10 to 40.

list = []
for i in range(15):
    x = random.randint(10,41)
    list.append(x)
# print(list)
print(np.array(list))

[28 24 14 27 23 29 27 32 15 41 37 18 30 35 15]


In [52]:
arr = np.random.randint(10,40,15)
print(arr)

[18 35 29 24 14 29 28 35 25 34 10 37 16 35 36]


In [53]:
#9. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

print(np.arange(10,22).reshape(3,4))


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [54]:
# 10. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# hello

In [55]:
# 11. Write a NumPy program to find the number of rows and columns in a given matrix


matrix = [[6,14 ,1],
          [56,12,122],
          [99,88,77]]

x = np.array(matrix)
print(x)

[[  6  14   1]
 [ 56  12 122]
 [ 99  88  77]]


In [56]:
row,col =  x.shape
print(row,col)

3 3


In [57]:
# 12 .Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

identity_matrix = np.diag([1,2,3,4,5])
print(identity_matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [58]:
dict = {}
list1 = ["A","B","C","D","E","F","G","H","I","J"]
list2 = [1,2,3,4,5,6,7,8,9,10]
j = 0
for i in list1:
    dict[i] = j
    j = j+1

print(dict)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9}


In [59]:
dict = {
    "name" : ["John" ,"Vaishnavi","Rahul"],
    "batch" : ["dbda" , "dbda" , "dac"],
    "roll no" : [101,201,301]
 }

df = pd.DataFrame(dict)
df

name batch  roll no
0       John  dbda      101
1  Vaishnavi  dbda      201
2      Rahul   dac      301

In [60]:
# 22 .i) Create a list of empids and names (10 employees).
#    ii) Convert list into Series.
#    iii) Print type of Series.
#    iv) Convert Series into DataFrame.
#    v) a) Display all records.
#       b) Display first five records.
#       c) Display last five records.
#       d) Display first two and last two records.
#       e) Display name of 5th employee.
#       f) Display record of 4th employee.
#    vi) Save the record in csv file (MyRecord.csv)

list_id =[1,2,3,4,5,6,7,8,9,10]
list_name = ["john","abhi","rahul","sneha","madhvi","tanzeel","shekar","vaishnavi","pawan","rohini"]
# arr = np.array(list1)
series = pd.Series(list_name,index=list_id)
print(series)

1          john
2          abhi
3         rahul
4         sneha
5        madhvi
6       tanzeel
7        shekar
8     vaishnavi
9         pawan
10       rohini
dtype: object


In [61]:
df = pd.DataFrame(series)
print(df)

            0
1        john
2        abhi
3       rahul
4       sneha
5      madhvi
6     tanzeel
7      shekar
8   vaishnavi
9       pawan
10     rohini


In [62]:
df.columns = ["Name"]
print(df)

         Name
1        john
2        abhi
3       rahul
4       sneha
5      madhvi
6     tanzeel
7      shekar
8   vaishnavi
9       pawan
10     rohini


In [63]:
print(df.head(5))
print(df.tail(5))

print(df.head(2))
print(df.tail(2))

print(df.iloc[4])
print(df.iloc[3])

     Name
1    john
2    abhi
3   rahul
4   sneha
5  madhvi
         Name
6     tanzeel
7      shekar
8   vaishnavi
9       pawan
10     rohini
   Name
1  john
2  abhi
      Name
9    pawan
10  rohini
Name    madhvi
Name: 5, dtype: object
Name    sneha
Name: 4, dtype: object


In [64]:
df.to_csv("names.csv")

In [65]:
Salary = ["45k","100k","90k","22k","30k","50k","77k","99k","200k","150k"]
df["Salary"] = Salary
print(df)
# print(df.iloc[10])
# df.iloc[11] = ["Damini","88k"]
# print(df)

         Name Salary
1        john    45k
2        abhi   100k
3       rahul    90k
4       sneha    22k
5      madhvi    30k
6     tanzeel    50k
7      shekar    77k
8   vaishnavi    99k
9       pawan   200k
10     rohini   150k


In [66]:
df = pd.read_csv("Salaries .csv")
print(df)

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]


In [67]:
# 24. Refer the dataset "Advertising.csv" and perform following tasks.
# i) Read the dataset "Advertising.csv" in data frame.

# ii) Print first five records of dataset.

# iii) print last five records from dataset.

# iv) display the column names of the dataset.

# v) display last three records from dataset.

# vi) display the information about the dataset and analyse the data.

# vii) display data types of each columns.
 
# viii) check for null values in the dataset and display the sum of null values inside the column.

# ix) drop a column 'radio' from a dataset and display first ten records.

# x) increase the sales by 10% and add a new column "updated_sales" in dataframe.

# xi) display shape of data.


df = pd.read_csv("Advertising.csv")
print(df)

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]


In [68]:
print(len(df))

200


In [69]:
df.loc[len(df)] = [240,40,50,60]
print(df)

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4
200  240.0   40.0       50.0   60.0

[201 rows x 4 columns]


In [70]:
print(df.head(5))
print(df.tail(5))
print(df.columns)

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9
        TV  radio  newspaper  sales
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4
200  240.0   40.0       50.0   60.0
Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')


In [71]:
df.describe()

TV       radio   newspaper       sales
count  201.000000  201.000000  201.000000  201.000000
mean   147.504975   23.347264   30.650746   14.251244
std     85.889963   14.856618   21.767363    6.132113
min      0.700000    0.000000    0.300000    1.600000
25%     74.700000   10.000000   12.800000   10.400000
50%    149.800000   23.300000   25.900000   12.900000
75%    219.800000   36.600000   45.100000   17.400000
max    296.400000   49.600000  114.000000   60.000000

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 201 entries, 0 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         201 non-null    float64
 1   radio      201 non-null    float64
 2   newspaper  201 non-null    float64
 3   sales      201 non-null    float64
dtypes: float64(4)
memory usage: 7.9 KB


In [73]:
df.count()

TV           201
radio        201
newspaper    201
sales        201
dtype: int64

In [74]:
print(len(df.columns))
print(len(df))

4
201


In [75]:
print(df.dtypes)

TV           float64
radio        float64
newspaper    float64
sales        float64
dtype: object


In [76]:
print(df.isnull())
print(df.isnull().sum())

        TV  radio  newspaper  sales
0    False  False      False  False
1    False  False      False  False
2    False  False      False  False
3    False  False      False  False
4    False  False      False  False
..     ...    ...        ...    ...
196  False  False      False  False
197  False  False      False  False
198  False  False      False  False
199  False  False      False  False
200  False  False      False  False

[201 rows x 4 columns]
TV           0
radio        0
newspaper    0
sales        0
dtype: int64


In [77]:
df = df.drop("radio",axis=1)
df

TV  newspaper  sales
0    230.1       69.2   22.1
1     44.5       45.1   10.4
2     17.2       69.3    9.3
3    151.5       58.5   18.5
4    180.8       58.4   12.9
..     ...        ...    ...
196   94.2        8.1    9.7
197  177.0        6.4   12.8
198  283.6       66.2   25.5
199  232.1        8.7   13.4
200  240.0       50.0   60.0

[201 rows x 3 columns]

In [78]:
df["New Sales"] = df["sales"] + (df["sales"] * 0.1)
# df
df.head(10)

TV  newspaper  sales  New Sales
0  230.1       69.2   22.1      24.31
1   44.5       45.1   10.4      11.44
2   17.2       69.3    9.3      10.23
3  151.5       58.5   18.5      20.35
4  180.8       58.4   12.9      14.19
5    8.7       75.0    7.2       7.92
6   57.5       23.5   11.8      12.98
7  120.2       11.6   13.2      14.52
8    8.6        1.0    4.8       5.28
9  199.8       21.2   10.6      11.66

In [79]:
df.shape

(201, 4)

In [80]:
df1 = pd.read_csv("Salaries .csv")
df1

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [81]:
print(df1.head(5))
print(df1.head(10))
print(df1.tail(5))
print(df1.tail(10))

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800
        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800
         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19       

In [82]:
print(df1.columns)
print("*****************************************************************************")
print(df1.shape)
print("*****************************************************************************")
print(df1.describe())

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')
*****************************************************************************
(78, 6)
*****************************************************************************
             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000


In [83]:
df1.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [84]:
max = df1.max()
print(max)

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object


In [85]:
min = df1.min()
print(min)

rank          AssocProf
discipline            A
phd                   1
service               0
sex              Female
salary            57800
dtype: object


In [91]:
mean = df1["salary"].mean()
print(mean)
print(70*"*")
median = df1["salary"].median()
print(median)
print(70*"*")
std = df1["salary"].std()
print(std)
# print(mean,median,std)


# ******

108023.78205128205
**********************************************************************
104671.0
**********************************************************************
28293.66102226417


In [87]:
df1.isnull().sum()

rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64

In [88]:
df1.dropna()
df1

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [95]:
# a) display records whose salary is greater than 50000.
#      b) display records whose salary is less than 20000.
#      c) display records whose salary is between 20000 to 50000.
#      d) display records whose salary is greater than 100000.
#      e) display records whose salary is less than 100000.

x1 = df1[df1["salary"] > 50000]
x1

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [94]:
x2 = df1[df1["salary"]<20000]
x2

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

In [104]:
x3 = df1[(df1["salary"] > 20000) & (df1["salary"] < 50000)]
# fi =   df[(df['Salary'] >= 20000) & (df['Salary'] <= 50000)]
x3

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

In [107]:
df1.describe()

phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [108]:
x4 = df1[df1["salary"] > 100000]
x4

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
7        Prof          A   18       18    Male  126300
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
65       Prof          A   36       19  Female  117555
69       Prof          A   28        7  Female  116450
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [109]:
x5 = df1[df1["salary"]<100000]
x5

rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
6   AssocProf          A   20       17    Male   81285
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
12   AsstProf          B    1        0    Male   88000
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
38   AsstProf          B    4        3    Male   91000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
46   AsstProf          B   11        3  Female   74692
50   AsstProf          B   10        5  Female   97032
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
60   AsstProf          B    3        3  Female   92000
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065

In [113]:
# a) display records whose discipline is A.
#      b) display records whose discipline is B.
#      c) display records whose service is greater than 10.
#      d) display records whose service is less than 5.

y1 = df1[df1["discipline"] == "A"]
y1

rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
32       Prof          A   27       19    Male  103275
37       Prof          A   20        8    Male  102000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [114]:
y2 = df1[df1["discipline"] == "B"]
y2

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
4        Prof          B   20       18    Male  104800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312

In [115]:
y3 = df1[df1["service"] >= 10]
y3

rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
54  AssocProf          A   25       22  Female   62884
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
67       Prof          A   17       11  Female   90450
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [117]:
y4 = df1[df1["service"] <= 5]
y4

rank discipline  phd  service     sex  salary
12  AsstProf          B    1        0    Male   88000
15      Prof          B   17        3    Male  150480
16  AsstProf          B    8        3    Male   75044
17  AsstProf          B    4        0    Male   92000
20  AsstProf          B    4        4    Male   92000
22  AsstProf          A    4        2    Male   73000
23  AsstProf          A    2        0    Male   85000
28  AsstProf          B    7        2    Male   91300
38  AsstProf          B    4        3    Male   91000
42  AsstProf          B    4        2  Female   80225
43  AsstProf          B    5        0  Female   77000
46  AsstProf          B   11        3  Female   74692
50  AsstProf          B   10        5  Female   97032
52      Prof          A   12        0  Female  105000
53  AsstProf          A    5        3  Female   73500
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
60  AsstProf          B    3        3  Female   92000
68  AsstProf          A    4        2  Female   77500
70  AsstProf          A    8        3  Female   78500

In [ ]:
# a) display records of phd and salary.
#      b) display records of rank, sex and salary.
#      c) display records without salary.
#      d) display first 50 records with rank,service and salary.
#      e) display records whose rank is Prof.
#      f) display records whose rank is AssocProf. 




#not able to get this in single table

In [124]:
z1  = [df1["phd"],df1["salary"]]
z1

[0     56
 1     12
 2     23
 3     40
 4     20
       ..
 73    18
 74    19
 75    17
 76    28
 77    23
 Name: phd, Length: 78, dtype: int64,
 0     186960
 1      93000
 2     110515
 3     131205
 4     104800
        ...  
 73    105450
 74    104542
 75    124312
 76    109954
 77    109646
 Name: salary, Length: 78, dtype: int64]

In [119]:
z6 = df1[df1["sex"] == "Male"]
z1

rank discipline  phd  service   sex  salary
0        Prof          B   56       49  Male  186960
1        Prof          A   12        6  Male   93000
2        Prof          A   23       20  Male  110515
3        Prof          A   40       31  Male  131205
4        Prof          B   20       18  Male  104800
5        Prof          A   20       20  Male  122400
6   AssocProf          A   20       17  Male   81285
7        Prof          A   18       18  Male  126300
8        Prof          A   29       19  Male   94350
9        Prof          A   51       51  Male   57800
10       Prof          B   39       33  Male  128250
11       Prof          B   23       23  Male  134778
12   AsstProf          B    1        0  Male   88000
13       Prof          B   35       33  Male  162200
14       Prof          B   25       19  Male  153750
15       Prof          B   17        3  Male  150480
16   AsstProf          B    8        3  Male   75044
17   AsstProf          B    4        0  Male   92000
18       Prof          A   19        7  Male  107300
19       Prof          A   29       27  Male  150500
20   AsstProf          B    4        4  Male   92000
21       Prof          A   33       30  Male  103106
22   AsstProf          A    4        2  Male   73000
23   AsstProf          A    2        0  Male   85000
24       Prof          A   30       23  Male   91100
25       Prof          B   35       31  Male   99418
26       Prof          A   38       19  Male  148750
27       Prof          A   45       43  Male  155865
28   AsstProf          B    7        2  Male   91300
29       Prof          B   21       20  Male  123683
30  AssocProf          B    9        7  Male  107008
31       Prof          B   22       21  Male  155750
32       Prof          A   27       19  Male  103275
33       Prof          B   18       18  Male  120000
34  AssocProf          B   12        8  Male  119800
35       Prof          B   28       23  Male  126933
36       Prof          B   45       45  Male  146856
37       Prof          A   20        8  Male  102000
38   AsstProf          B    4        3  Male   91000