In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot  as plt
import seaborn as sns

2023-11-28 14:50:19.167610: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-28 14:50:19.907361: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-28 14:50:19.907409: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-28 14:50:19.949065: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-28 14:50:19.998073: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-28 14:50:20.011364: I tensorflow/core/platform/cpu_feature_guard.cc:1

## 1 a)

In [2]:
df = pd.read_csv("NewspaperData.csv")
df

Newspaper     daily    sunday
0                    Baltimore Sun   391.952   488.506
1                     Boston Globe   516.981   798.298
2                    Boston Herald   355.628   235.084
3               Charlotte Observer   238.555   299.451
4                Chicago Sun Times   537.780   559.093
5                  Chicago Tribune   733.775  1133.249
6              Cincinnati Enquirer   198.832   348.744
7                      Denver Post   252.624   417.779
8              Des Moines Register   206.204   344.522
9                 Hartford Courant   231.177   323.084
10               Houston Chronicle   449.755   620.752
11                Kansas City Star   288.571   423.305
12         Los Angeles Daily  News   185.736   202.614
13               Los Angeles Times  1164.388  1531.527
14                    Miami Herald   444.581   553.479
15        Minneapolis Star Tribune   412.871   685.975
16      New Orleans Times-Picayune   272.280   324.241
17             New York Daily News   781.796   983.240
18                  New York Times  1209.225  1762.015
19                         Newsday   825.512   960.308
20              Omaha World Herald   223.748   284.611
21          Orange County Register   354.843   407.760
22           Philadelphia Inquirer   515.523   982.663
23                Pittsburgh Press   220.465   557.000
24              Portland Oregonian   337.672   440.923
25     Providence Journal-Bulletin   197.120   268.060
26  Rochester Democrat & Chronicle   133.239   262.048
27             Rocky Mountain News   374.009   432.502
28                  Sacramento Bee   273.844   338.355
29         San Francisco Chronicle   570.364   704.322
30         St. Louis Post-Dispatch   391.286   585.681
31          St. Paul Pioneer Press   201.860   267.781
32                   Tampa Tribune   321.626   408.343
33                 Washington Post   838.902  1165.567

In [4]:
df.drop("Newspaper",axis=1,inplace=True)

In [5]:
df

daily    sunday
0    391.952   488.506
1    516.981   798.298
2    355.628   235.084
3    238.555   299.451
4    537.780   559.093
5    733.775  1133.249
6    198.832   348.744
7    252.624   417.779
8    206.204   344.522
9    231.177   323.084
10   449.755   620.752
11   288.571   423.305
12   185.736   202.614
13  1164.388  1531.527
14   444.581   553.479
15   412.871   685.975
16   272.280   324.241
17   781.796   983.240
18  1209.225  1762.015
19   825.512   960.308
20   223.748   284.611
21   354.843   407.760
22   515.523   982.663
23   220.465   557.000
24   337.672   440.923
25   197.120   268.060
26   133.239   262.048
27   374.009   432.502
28   273.844   338.355
29   570.364   704.322
30   391.286   585.681
31   201.860   267.781
32   321.626   408.343
33   838.902  1165.567

In [6]:
x = df["daily"]
y = df["sunday"]

In [7]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [18]:
# model = Sequential()
# model.add([Dense(units = 1 , input_shape = [1])])
model = Sequential([Dense(units=1, input_shape=[1])])
model.compile(optimizer = "sgd" , loss = "mean_absolute_error")
model.fit(x,y,epochs = 100)

Epoch 1/100
2/2 [==============================] - 0s 4ms/step - loss: 1170.3004
Epoch 2/100
2/2 [==============================] - 0s 3ms/step - loss: 806.5937
Epoch 3/100
2/2 [==============================] - 0s 4ms/step - loss: 387.7144
Epoch 4/100
2/2 [==============================] - 0s 4ms/step - loss: 1880.7318
Epoch 5/100
2/2 [==============================] - 0s 3ms/step - loss: 995.2631
Epoch 6/100
2/2 [==============================] - 0s 4ms/step - loss: 1794.0052
Epoch 7/100
2/2 [==============================] - 0s 4ms/step - loss: 1059.4911
Epoch 8/100
2/2 [==============================] - 0s 3ms/step - loss: 235.5163
Epoch 9/100
2/2 [==============================] - 0s 4ms/step - loss: 364.8664
Epoch 10/100
2/2 [==============================] - 0s 4ms/step - loss: 229.1818
Epoch 11/100
2/2 [==============================] - 0s 6ms/step - loss: 86.5411
Epoch 12/100
2/2 [==============================] - 0s 3ms/step - loss: 1484.7500
Epoch 13/100
2/2 [===============

In [15]:
model.predict([500.0])

1/1 [==============================] - 0s 29ms/step


array([[573.66284]], dtype=float32)

# b)

In [19]:
df2 = pd.read_csv("delivery_time.csv")
df2

Delivery Time  Sorting Time
0           21.00            10
1           13.50             4
2           19.75             6
3           24.00             9
4           29.00            10
5           15.35             6
6           19.00             7
7            9.50             3
8           17.90            10
9           18.75             9
10          19.83             8
11          10.75             4
12          16.68             7
13          11.50             3
14          12.03             3
15          14.88             4
16          13.75             6
17          18.11             7
18           8.00             2
19          17.83             7
20          21.50             5

In [26]:
df2.columns

Index(['Delivery Time', 'Sorting Time'], dtype='object')

In [27]:
x = df2["Delivery Time"]
y = df2["Sorting Time"]

In [36]:
model = Sequential([Dense(units = 1 , input_shape = [1])])
model.compile(optimizer = "sgd", loss = "mean_absolute_error")
model.fit(x,y,epochs = 100)

Epoch 1/100
1/1 [==============================] - 0s 176ms/step - loss: 22.2401
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 19.4107
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 16.5813
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 13.7520
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 10.9226
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 8.0933
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 5.2639
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 2.5108
Epoch 9/100
1/1 [==============================] - 0s 4ms/step - loss: 1.1115
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 1.1559
Epoch 11/100
1/1 [==============================] - 0s 7ms/step - loss: 1.2476
Epoch 12/100
1/1 [==============================] - 0s 4ms/step - loss: 1.1380
Epoch 13/100
1/1 [==============================] - 0s

In [37]:
model.predict([15])

1/1 [==============================] - 0s 49ms/step


array([[4.8900895]], dtype=float32)

## c)

In [38]:
df3 = pd.read_csv("WC_AT.csv")
df3

Waist      AT
0     74.75   25.72
1     72.60   25.89
2     81.80   42.60
3     83.95   42.80
4     74.65   29.84
..      ...     ...
104  100.10  124.00
105   93.30   62.20
106  101.80  133.00
107  107.90  208.00
108  108.50  208.00

[109 rows x 2 columns]

In [40]:
x = df3["Waist"]
y = df3["AT"]

In [43]:
model = Sequential([Dense(units = 1 , input_shape = [1])])
model.compile(optimizer = "sgd" , loss = "mean_absolute_error")
model.fit(x,y,epochs = 100)

Epoch 1/100
4/4 [==============================] - 0s 2ms/step - loss: 113.5601
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 37.2395
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 41.5579
Epoch 4/100
4/4 [==============================] - 0s 2ms/step - loss: 37.8207
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 37.0796
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 37.9898
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 40.0622
Epoch 8/100
4/4 [==============================] - 0s 2ms/step - loss: 38.8874
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 37.1560
Epoch 10/100
4/4 [==============================] - 0s 2ms/step - loss: 38.2945
Epoch 11/100
4/4 [==============================] - 0s 3ms/step - loss: 39.0868
Epoch 12/100
4/4 [==============================] - 0s 2ms/step - loss: 39.4618
Epoch 13/100
4/4 [==============================

In [44]:
model.predict([100])

1/1 [==============================] - 0s 47ms/step


array([[108.76818]], dtype=float32)